config/routes.rb
Rails.application.routes.draw do
  match 'digital_assets/search' => 'digital_assets#search'
  post "digital_assets/sync" => 'digital_assets#sync_assets'
  # match 'digital_assets/:id' => 'digital_assets#sami'  #, :id => /\w{4,8}.\d*/
  resources :digital_assets, :only => [:index, :show]
  #resources :digital_assets
  #get 'digital_assets' => 'digital_asset#index'
end

app/models/digital_asset.rb
require 'mongoid'

class DigitalAsset
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :changed_at, type: Time
  field :audiences, type: Array, default: []
  field :sami_code, type: String
  field :product_ids, type: Array, default: []
  field :published_at, type: Time
  field :unpublished_at, type: Time
  field :expires_at, type: Time  
  field :guid, type: String
  field :fund_ids, type: Array, default: []
  field :business_owner, type: String
  field :summary, type: String

  key :guid

  # field :documents, type: Hash

  embeds_many :documents, :class_name => 'DigitalAsset::Document'

  accepts_nested_attributes_for :documents

  scope :title_is, ->(title) { where(:title => title)}
  scope :business_owner_is, ->(business_owner) { where(:business_owner => business_owner)}
  scope :guid_is, ->(guid) { where(:guid => guid)}
  scope :funds_in, ->(fund_id) { where(:fund_ids.in => fund_id)}
  scope :audience_in, ->(audience_id) {where(:audiences.in => audience_id)}
  scope :sami_is, ->(sami_code) {where(:sami_code => sami_code)}
  scope :path_is, ->(path) {where(:'documents.path' => path)}
  scope :doctype_in, ->(types) {where(:'documents.content_type'.in => types)}
  scope :product_in, ->(types) {where(:product_ids.in => types)}
  scope :stale, -> {where(:updated_at.lte => 2.minutes.ago)}

  # validations
  validates_presence_of :guid, :title, :changed_at, :published_at, 
      :expires_at, :audiences, :documents

  validate :validate_future_expiration

  # validates_uniqueness_of :guid

  def self.purge!
    # last_update = DigitalAsset.desc(:updated_at).try(:first).try :updated_at
    DigitalAsset.stale.destroy_all if bulk_processed?
  end

  def validate_future_expiration
    errors.add(:expires_at, "Expiration date must be at least 1 minute from now") unless expires_at and expires_at > 1.minute.from_now
  end

  def self.bulk_processed?
    (stale.count.to_f / self.count) <= 0.05
  end
end

class DigitalAsset::Document
  include Mongoid::Document

  field :path, type: String
  field :doc_changed_at, type: Time
  field :content_type, type: String
  embedded_in :digital_asset

  key :path

  validates_uniqueness_of :path

  validates_presence_of :path #, :doc_changed_at, :content_type
  validates_format_of :path, without: /\/manifest|archives\// # dont accept manifest files

end

app/controllers/digital_assets_controller.rb
class DigitalAssetsController < ApplicationController

  respond_to :json, :html, :only => [:index, :show, :search]

  CACHE_LAST_PARSE_TIME = 'last_parse_time'
  # GET /digital_assets
  # GET /digital_assets.json
  def index
    @digital_assets = DigitalAsset.all
    respond_with(@digital_assets)
  end

  # GET /digital_assets/1
  # GET /digital_assets/1.json
  def show
    @digital_asset = /\w{4,8}\.\d{0,3}/ =~ params[:id] ? DigitalAsset.sami_is(params[:id]).desc(:changed_at).first : DigitalAsset.find(params[:id])
    respond_with(@digital_asset)
  end

  #/digital_assets/search/sami_code=92023
  #/digital_assets/search/sami_code=NE00192&title=Fund%20Prospectus&fund_code=20293
  def search
    @digital_assets = []
    # loop thru each parameter that matches one of the method signatures
    @digital_assets = params.keys.select do |pk|
      DigitalAsset.respond_to?("#{pk}_is".to_sym) or DigitalAsset.respond_to?("#{pk}_in".to_sym)
    end.reduce(DigitalAsset) do |sum, key|
      # for each key, call the 'named query' method with the value given and chain...
      method = DigitalAsset.respond_to?("#{key}_in".to_sym) ? "#{key}_in".to_sym : "#{key}_is".to_sym
      sum.send(method, method.to_s.end_with?('in') ? params[key].to_a : params[key]) # should return result of the send call for chaining
    end
    respond_with(@digital_assets)
  end

  def sync_assets
    time0 = Rails.cache.read(CACHE_LAST_PARSE_TIME)
    if time0.nil?
      time0 = 2.days.ago
    end
    logger.info "Last time when ssc deploy files were read: #{time0.inspect}"
    time1 = Time.new
    logger.info "Current time: #{time1.inspect}"

    Rails.cache.write(CACHE_LAST_PARSE_TIME, time1)
    deploy_files= []

    start_directory = EDIST['digital_assets_directory']
    logger.info "Reading digital asset deployment files from #{start_directory}"
    if (File::directory?(start_directory))
      Dir.foreach(start_directory) do |entry|
        if (!File::directory?(entry))
          filename = start_directory + entry
          difference0 = File.mtime(filename)- time0 #To-Do - We should be looking at created time - ctime
          difference1 = File.mtime(filename) - time1
          if ((difference0 >= 0) & (difference1 < 0))
            if(/bulk-ssc_|selective-ssc_/ =~ filename)
              deploy_files << filename
            end
          end
        end
      end
    end

    deploy_files.each do |filename|
      #parse the file and add content to database.
      logger.info "Processing file #{filename} found."
      file = File.expand_path(filename, __FILE__)
      open_file = open(file, 'rb')
      Etl::TeamsiteMetadataParser.parse_tuple_file(open_file)
      logger.info "Finished parsing #{filename}."
    end

    head :accepted
  end

end

app/helpers/digital_assets_helper.rb
module DigitalAssetsHelper
end

app/views/digital_assets/_form.html.erb
<%= form_for(@digital_asset) do |f| %>
  <% if @digital_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@digital_asset.errors.count, "error") %> prohibited this digital_asset from being saved:</h2>

      <ul>
      <% @digital_asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/digital_assets/edit.html.erb
<h1>Editing digital_asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @digital_asset %> |
<%= link_to 'Back', digital_assets_path %>

app/views/digital_assets/index.html.erb
<h1>Listing digital_assets</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Guid</th>
    <th>Updated at</th>
    <th>Audience</th>
    <th>Sami code</th>
    <th>Product</th>
    <th>Published at</th>
    <th>Expires at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @digital_assets.each do |digital_asset| %>
      <tr>
        <td><%= digital_asset.title %></td>
        <td><%= digital_asset.guid %></td>
        <td><%= digital_asset.changed_at %></td>
        <td><%= digital_asset.audiences %></td>
        <td><%= digital_asset.sami_code %></td>
        <td><%= digital_asset.product_ids %></td>
        <td><%= digital_asset.published_at %></td>
        <td><%= digital_asset.expires_at %></td>
        <td><%= link_to 'Show', digital_asset %></td>
      </tr>
  <% end %>
</table>

<br/>

app/views/digital_assets/new.html.erb
<h1>New digital_asset</h1>

<%= render 'form' %>

<%= link_to 'Back', digital_assets_path %>

app/views/digital_assets/search.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Sami code</th>
    <th>Products</th>
    <th>Updated at</th>
    <th>Published at</th>
    <th>Expires at</th>
    <th>Guid</th>
  </tr>

  <% @digital_assets.each do |digital_asset| %>
      <tr>
        <td><%= digital_asset.title %></td>
        <td><%= digital_asset.sami_code %></td>
        <td><%= digital_asset.product_ids.join(", ") %></td>
        <td><%= digital_asset.changed_at %></td>
        <td><%= digital_asset.published_at %></td>
        <td><%= digital_asset.expires_at %></td>
        <td><%= digital_asset.guid %></td>
        <td><%= link_to 'Show', digital_asset %></td>
      </tr>
  <% end %>
</table>

<div>
  <h2>Current Documents</h2>
  <% @digital_assets.each do |digital_asset| %>
      <% if digital_asset.documents.size > 0 %>
          <table>
            <tr>
              <th>Content Type</th>
              <th>Path</th>
            </tr>
            <% for document in digital_asset.documents %>
                <tr>
                  <td><%= document.content_type %></td>
                  <td><%= document.path %></td>
                </tr>
            <% end %>
          </table>
      <% end %>
  <% end %>

</div>

app/views/digital_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @digital_asset.title %>
</p>

<p>
  <b>Updated at:</b>
  <%= @digital_asset.updated_at %>
</p>

<p>
  <b>Audience:</b>
  <%= @digital_asset.audiences %>
</p>

<p>
  <b>Sami code:</b>
  <%= @digital_asset.sami_code %>
</p>

<p>
  <b>Program:</b>
  <%= @digital_asset.product_ids %>
</p>

<p>
  <b>Published at:</b>
  <%= @digital_asset.published_at %>
</p>

<p>
  <b>Expires at:</b>
  <%= @digital_asset.expires_at %>
</p>

<p>
  <b>Guid:</b>
  <%= @digital_asset.guid %>
</p>

<% if @digital_asset.documents.size > 0 %>
    <h2>Current Documents</h2>
    <table>
      <tr>
        <th>Content Type</th>
        <th>Path</th>
      </tr>
      <% for document in @digital_asset.documents %>
          <tr>
            <td><%= document.content_type %></td>
            <td><%= document.path %></td>
          </tr>
      <% end %>
    </table>
<% end %>